name: release-solution-to-prod-reusable
# Reusable workflow
# upload the solution to the GitHub artifacts and deploy to the PROD environment
on:
  workflow_call:
    inputs: 
      #Do Not change these values
      #Values are set by the caller
      #caller sample: release-action-call.ymnl
      AZURE_FUNCTIONAPP_NAME:
        description: 'The azure function app name.'
        type: string
        default: ModernEmployees 
      AZURE_FUNCTIONAPP_PACKAGE_PATH:
        description: 'The azure function app package path .'
        type: string
        default: .   
      DOTNET_VERSION:
        description: 'dot net version run time.'
        type: string
        default: 3.0.13    
    secrets:
      envSecret:
        description: 'The secret value for authentication using SPN'
        required: true
jobs:
  build-and-deploy:
    name: Continuous Deployment - Development
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup DotNet 8.0.x Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.DOTNET_VERSION }}

      - name: Resolve Project Dependencies Using Dotnet
        shell: bash
        run: |
          pushd './${{ inputs.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ inputs.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ inputs.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.envSecret }}