name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
on:
  # release:
  #     types: [created]     
  push:
    branches: [ "Master" ]
permissions:
  contents: write
jobs:
  Release-solution:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      AZURE_FUNCTIONAPP_NAME: pocazurefunction11
      AZURE_FUNCTIONAPP_PACKAGE_PATH: './Code'
      DOTNET_VERSION: '8.0.x'
    secrets:
      envSecret: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE  }}